
name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - re

  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib
    - seaborn
    - bs4
    - trueskill

    - glob
    - collections
    - sklearn
    
    
