
name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy


  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib
    - math
    - seaborn
    - bs4
    - trueskill
    - re
    - glob
    - collections
    - sklearn
    
    
